<template>
  <div class="designers">
    <h1>designers</h1>
    <h2>aeufhkuhnds</h2>
  </div>
</template>

<script>
export default {
  name: 'designers'
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h1,
h2 {
  font-weight: normal;
}

h1 {
    font-weight: 500;
    font-size: 50px;
    padding-bottom: 50px;
}

.designers {
    margin: auto;
    text-align: center;
    padding: 150px 0px 100px 0px;
    color: #2B3D4E;
}
</style>
